config/routes.rb
Project::Application.routes.draw do

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"
  resources :sessions, :only => [:create]

  resources :order_lines

  resources :order_headers

  resources :products

  resources :vendors

  resources :users

  root :to => 'home#index'

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  attr_accessible :cnpj, :fornecedor, :telefone, :tipo, :vendor_id

  has_many :OrderHeader

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @vendors }
    end
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @vendor }
    end
  end

  # GET /vendors/new
  # GET /vendors/new.json
  def new
    @vendor = Vendor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @vendor }
    end
  end

  # GET /vendors/1/edit
  def edit
    @vendor = Vendor.find(params[:id])
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(params[:vendor])

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, :notice => 'Vendor was successfully created.' }
        format.json { render :json => @vendor, :status => :created, :location => @vendor }
      else
        format.html { render :action => "new" }
        format.json { render :json => @vendor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vendors/1
  # PUT /vendors/1.json
  def update
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      if @vendor.update_attributes(params[:vendor])
        format.html { redirect_to @vendor, :notice => 'Vendor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @vendor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy

    respond_to do |format|
      format.html { redirect_to vendors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cnpj %><br />
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    <%= f.label :fornecedor %><br />
    <%= f.text_field :fornecedor %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Cadastro de Fornecedores</h1>

<fieldset style="width:25%">
  <legend>Editar dados</legend>
<%= render 'form' %>
</fieldset>
<%= link_to 'Exibir', @vendor %> |
<%= link_to 'Voltar', vendors_path %>

app/views/vendors/index.html.erb
<h1>Cadastro de Fornecedor</h1>

<table style="border-style:solid; border-width:1">
  <tr>
    <th align='left'>Cnpj</th>
    <th align='left'>Fornecedor</th>
    <th align='left'>Tipo</th>
    <th align='left'>Telefone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vendors.each do |vendor| %>
  <tr>
    <td width=150><%= vendor.cnpj %></td>
    <td width=350><%= vendor.fornecedor %></td>
    <td width=150><%= vendor.tipo %></td>
    <td width=100><%= vendor.telefone %></td>
    <td><%= link_to 'Exibir', vendor %></td>
    <td><%= link_to 'Editar', edit_vendor_path(vendor) %></td>
    <td><%= link_to 'Excluir', vendor, :confirm => 'Deseja excluir o registro selecionado?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Inserir fornecedor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>Cadastro de Fornecedores</h1>

<fieldset>
  <legend> Criar usuário</legend>
<%= render 'form' %>
</fieldset>
<%= link_to 'Voltar', vendors_path %>

app/views/vendors/show.html.erb
<fieldset style="width:35%">
  <legend>Dados do usuário</legend>
<p id="notice"><%= notice %></p>

<p>
  <b>Cnpj:</b>
  <%= @vendor.cnpj %>
</p>

<p>
  <b>Fornecedor:</b>
  <%= @vendor.fornecedor %>
</p>

<p>
  <b>Tipo:</b>
  <%= @vendor.tipo %>
</p>

<p>
  <b>Telefone:</b>
  <%= @vendor.telefone %>
</p>
</fieldset>

<%= link_to 'Editar', edit_vendor_path(@vendor) %> |
<%= link_to 'Voltar', vendors_path %>