config/routes.rb
Project::Application.routes.draw do

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"
  resources :sessions, :only => [:create]

  resources :order_lines

  resources :order_headers

  resources :products

  resources :vendors

  resources :users

  root :to => 'home#index'

end

app/models/order_header.rb
class OrderHeader < ActiveRecord::Base
  attr_accessible :aviso, :order, :vendor_id, :po_header_id

  belongs_to :vendor
  has_many :order_lines

  validates_presence_of :order
end

app/controllers/order_headers_controller.rb
class OrderHeadersController < ApplicationController
  # GET /order_headers
  # GET /order_headers.json
  def index
    @order_headers = OrderHeader.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @order_headers }
    end
  end

  # GET /order_headers/1
  # GET /order_headers/1.json
  def show
    @order_header = OrderHeader.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @order_header }
    end
  end

  # GET /order_headers/new
  # GET /order_headers/new.json
  def new
    @order_header = OrderHeader.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @order_header }
    end
  end

  # GET /order_headers/1/edit
  def edit
    @order_header = OrderHeader.find(params[:id])
  end

  # POST /order_headers
  # POST /order_headers.json
  def create
    @order_header = OrderHeader.new(params[:order_header])

    respond_to do |format|
      if @order_header.save
        format.html { redirect_to @order_header, :notice => 'Order header was successfully created.' }
        format.json { render :json => @order_header, :status => :created, :location => @order_header }
      else
        format.html { render :action => "new" }
        format.json { render :json => @order_header.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /order_headers/1
  # PUT /order_headers/1.json
  def update
    @order_header = OrderHeader.find(params[:id])

    respond_to do |format|
      if @order_header.update_attributes(params[:order_header])
        format.html { redirect_to @order_header, :notice => 'Order header was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @order_header.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /order_headers/1
  # DELETE /order_headers/1.json
  def destroy
    @order_header = OrderHeader.find(params[:id])
    @order_header.destroy

    respond_to do |format|
      format.html { redirect_to order_headers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/order_headers_helper.rb
module OrderHeadersHelper
end

app/views/order_headers/_form.html.erb
<%= form_for(@order_header) do |f| %>
  <% if @order_header.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_header.errors.count, "error") %> prohibited this order_header from being saved:</h2>

      <ul>
      <% @order_header.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order %><br />
    <%= f.text_field :order %>
  </div>
  <div class="field">
    <%= f.label :vendor_id %><br />
    <%= f.number_field :vendor_id %>
  </div>
  <div class="field">
    <%= f.label :aviso %><br />
    <%= f.text_area :aviso %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_headers/edit.html.erb
<h1>Ordem de Compra</h1>

<fieldset style="width:25%">
  <legend>Editar dados</legend>
<%= render 'form' %>
</fieldset>
<%= link_to 'Exibir', @order_header %> |
<%= link_to 'Voltar', order_headers_path %>

app/views/order_headers/index.html.erb
<h1>Ordem de Compra</h1>

<table style="border-style:solid; border-width:1, width:25%">
  <tr>
    <th align='left'>Número da Ordem</th>
    <th align='left'>Fornecedor</th>
    <th align='left'>Aviso</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @order_headers.each do |order_header| %>
  <tr>
    <td width=150><%= order_header.order %></td>
    <td width=150><%= order_header.vendor.fornecedor %></td>
    <td width=300><%= order_header.aviso %></td>
    <td><%= link_to 'Exibir', order_header %></td>
    <td><%= link_to 'Editar', edit_order_header_path(order_header) %></td>
    <td><%= link_to 'Excluir', order_header, :confirm => 'Deseja excluir o registro selecionado?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Criar nova OC', new_order_header_path %>

app/views/order_headers/new.html.erb
<h1>Ordem de Compra</h1>

<fieldset style="width:25%">
  <legend> Criar nova OC</legend>
<%= render 'form' %>
</fieldset>
<%= link_to 'Voltar', order_headers_path %>

app/views/order_headers/show.html.erb
<fieldset style="width:35%">
  <legend>Resumo da Ordem de Compra</legend>

<p id="notice"><%= notice %></p>

<p>
  <b>Número da Ordem:</b>
  <%= @order_header.order %>
</p>

<p>
  <b>Fornecedor:</b>
  
  <%= @order_header.vendor.fornecedor %>
</p>

<p>
  <b>Aviso:</b>
  <%= @order_header.aviso %>
</p>
</fieldset>

<%= link_to 'Editar', edit_order_header_path(@order_header) %> |
<%= link_to 'Voltar', order_headers_path %>

<%= link_to 'Ir para as Linhas da OC', order_lines_path %>