config/routes.rb
Project::Application.routes.draw do

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"
  resources :sessions, :only => [:create]

  resources :order_lines

  resources :order_headers

  resources :products

  resources :vendors

  resources :users

  root :to => 'home#index'

end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  attr_accessible :complemento, :integer, :integer, :item_id, :po_header_id, :qtd, :vlrUnit

  belongs_to :order_header, :class_name => 'OrderHeader', :foreign_key => "po_header_id"
  belongs_to :product, :class_name => 'Product', :foreign_key => "item_id"

end

app/controllers/order_lines_controller.rb
class OrderLinesController < ApplicationController
  # GET /order_lines
  # GET /order_lines.json
  def index
    @order_lines = OrderLine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @order_lines }
    end
  end

  # GET /order_lines/1
  # GET /order_lines/1.json
  def show
    @order_line = OrderLine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @order_line }
    end
  end

  # GET /order_lines/new
  # GET /order_lines/new.json
  def new
    @order_line = OrderLine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @order_line }
    end
  end

  # GET /order_lines/1/edit
  def edit
    @order_line = OrderLine.find(params[:id])
  end

  # POST /order_lines
  # POST /order_lines.json
  def create
    @order_line = OrderLine.new(params[:order_line])

    respond_to do |format|
      if @order_line.save
        format.html { redirect_to @order_line, :notice => 'Order line was successfully created.' }
        format.json { render :json => @order_line, :status => :created, :location => @order_line }
      else
        format.html { render :action => "new" }
        format.json { render :json => @order_line.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /order_lines/1
  # PUT /order_lines/1.json
  def update
    @order_line = OrderLine.find(params[:id])

    respond_to do |format|
      if @order_line.update_attributes(params[:order_line])
        format.html { redirect_to @order_line, :notice => 'Order line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @order_line.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /order_lines/1
  # DELETE /order_lines/1.json
  def destroy
    @order_line = OrderLine.find(params[:id])
    @order_line.destroy

    respond_to do |format|
      format.html { redirect_to order_lines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/views/order_lines/_form.html.erb
<%= form_for(@order_line) do |f| %>
  <% if @order_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_line.errors.count, "error") %> prohibited this order_line from being saved:</h2>

      <ul>
      <% @order_line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :po_header_id %><br />
    <%= f.text_field :po_header_id %>
  </div>
  <div class="field">
    <%= f.label :integer %><br />
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br />
    <%= f.text_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :integer %><br />
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :vlrUnit %><br />
    <%= f.text_field :vlrUnit %>
  </div>
  <div class="field">
    <%= f.label :qtd %><br />
    <%= f.text_field :qtd %>
  </div>
  <div class="field">
    <%= f.label :complemento %><br />
    <%= f.text_area :complemento %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_lines/edit.html.erb
<h1>Linhas da Ordem de Compra</h1>

<fieldset style="width:25%">
  <legend>Editar dados</legend>
<%= render 'form' %>
</fieldset>

<%= link_to 'Exibir', @order_line %> |
<%= link_to 'Voltar', order_lines_path %>

app/views/order_lines/index.html.erb
<h1>Linhas da Ordem de Compra</h1>

<table style="border-style:solid; border-width:1">
  <tr>
    <th align='left'>Número da Ordem</th>
    <th align='left'>Item</th>
    <th align='left'>Valor unitário</th>
    <th align='left'>Qtd</th>
    <th align='left'>Complemento</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @order_lines.each do |order_line| %>
  <tr>
    <td width=50><%= order_line.order_header.order %></td>
    <td width=100><%= order_line.product.codigo %></td>
    <td width=100><%= order_line.vlrUnit %></td>
    <td width=15><%= order_line.qtd %></td>
    <td width=250><%= order_line.complemento %></td>
    <td><%= link_to 'Exibir', order_line %></td>
    <td><%= link_to 'Editar', edit_order_line_path(order_line) %></td>
    <td><%= link_to 'Deletar', order_line, :confirm => 'Você deseja deletar o registro selecionado?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Criar nova linha de OC', new_order_line_path %>
<%= link_to 'Voltar', order_headers_path %>

app/views/order_lines/new.html.erb
<h1>Linha da Ordem de Compra</h1>

<fieldset style="width:25%">
  <legend> Inserir nova linha</legend>
<%= render 'form' %>
</fieldset>
<%= link_to 'Voltar', order_lines_path %>

app/views/order_lines/show.html.erb
<fieldset style="width:35%">
  <legend>Linhas da OC</legend>

<p id="notice"><%= notice %></p>

<p>
  <b>Po header:</b>
  <%= @order_line.order_header.order %>
</p>

<p>
  <b>Item:</b>
  <%= @order_line.product.codigo %>
</p>

<p>
  <b>Vlrunit:</b>
  <%= @order_line.vlrUnit %>
</p>

<p>
  <b>Qtd:</b>
  <%= @order_line.qtd %>
</p>

<p>
  <b>Complemento:</b>
  <%= @order_line.complemento %>
</p>
</fieldset>

<%= link_to 'Editar', edit_order_line_path(@order_line) %> |
<%= link_to 'Voltar', order_lines_path %>