config/routes.rb
Project::Application.routes.draw do

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"
  resources :sessions, :only => [:create]

  resources :order_lines

  resources :order_headers

  resources :products

  resources :vendors

  resources :users

  root :to => 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :codigo, :descricao, :udm

  has_many :order_lines
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, :notice => 'Product was successfully created.' }
        format.json { render :json => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, :notice => 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :udm %><br />
    <%= f.text_area :udm %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Cadastro de Produtos</h1>

<fieldset style="width:25%">
  <legend>Editar dados do produto</legend>
<%= render 'form' %>
</fieldset>

<%= link_to 'Exibir', @product %> |
<%= link_to 'Voltar', products_path %>

app/views/products/index.html.erb
<center><h1>Listagem de Produtos</h1>

<table style="border-style:solid; border-width:1">
  <tr>
    <th align='left'>Código</th>
    <th align='left'>Descrição</th>
    <th align='left'>UDM</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.codigo %></td>
    <td><%= product.descricao %></td>
    <td><%= product.udm %></td>
    <td><%= link_to 'Exibir', product %></td>
    <td><%= link_to 'Editar', edit_product_path(product) %></td>
    <td><%= link_to 'Deletar', product, :confirm => 'Você deseja excluir o item selecionado?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
</center>
<%= link_to 'Inserir produto', new_product_path %>

app/views/products/new.html.erb
<h1>Cadastro de Produtos</h1>

<fieldset style="width:35%">
  <legend>Inserir Produto</legend>
<%= render 'form' %>
</fieldset>
<%= link_to 'Voltar', products_path %>

app/views/products/show.html.erb
<fieldset style="width:35%">
  <legend> Cadastro de produtos</legend>
<p id="notice"><%= notice %></p>

<p>
  <b>Código:</b>
  <%= @product.codigo %>
</p>

<p>
  <b>Descrição:</b>
  <%= @product.descricao %>
</p>

<p>
  <b>UDM:</b>
  <%= @product.udm %>
</p>
</fieldset>

<%= link_to 'Editar', edit_product_path(@product) %> |
<%= link_to 'Voltar', products_path %>